### PR TITLE
Ea user texts layout

### PR DESCRIPTION
**Pull request by eamon0989**
## Description

Added responsive grid and styling to the text page.
Added a card layout to both the user texts page and single text page.
Added basic styling to the translation input div.
Fixed a bug where languages were not loaded into state correctly upon sign-in.
Changed logo, clicking logo takes you to texts.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  X  | :bug: Bug fix              |
|     | :sparkles: New feature     |
|  X  | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### After
Screen Shot 2022-01-01 at 10 19 50
Screen Shot 2022-01-01 at 10 20 14
Screen Shot 2022-01-01 at 10 20 34

### CODE REVIEW

**Comment by danachen** [comment]
This is looking better and better! 🚀🔥🤩 

One thing I'm wondering around the translation component: the first time I was playing with the layout, I didn't realize I had to scroll all the way to the bottom of the dictionary to get to translation input and change status (sometimes the dictionary entry is long). Could this create a user experience issue?

**Comment by eamon0989** [comment]
I completely agree. I would like to try and come up with another solution if possible.

**Comment by danachen** [comment]
I will merge this now.

**Comment by mrchrmn** [comment]
See issue #64 regarding translation input layout.

**Pull request merged**
