### PR TITLE
Mh words page

### PR DESCRIPTION
**Pull request by mrchrmn**
## Description

This is an intermediate pull request in answer to Eamon's request of connecting to the Heroku app when running `npm start`, ie. from the development environment. 

You will have to create a `.env` file in your front end repository. ~~If it holds a variable `REACT_APP_DB_HOST` that points to the Heroku app URL, this will be used instead of `localhost`.~~ (see comment below)

~~The words page does not work, yet.~~ It does work after the back end fix.

### CODE REVIEW

**Comment by mrchrmn** [comment]
Both, development DB host and production DB host are now read from `.env`.
These are the variables you have to fill in. Both must exist for the app to run.
`REACT_APP_DEV_DB`
`REACT_APP_PROD_DB`

**Comment by mrchrmn** [comment]
Both, development DB host and production DB host are now read from `.env`.
These are the variables you have to fill in. Both must exist for the app to run.
`REACT_APP_DEV_DB`
`REACT_APP_PROD_DB`

**Comment by eamon0989** [comment]
Awesome thanks very much! I'm going out for a walk now, I'll try it once I get home 👍🏼 👏🏼

**Comment by mrchrmn** [comment]
With the latest fix on the back end, the words page works now (in a first version).

**Comment by mrchrmn** [comment]
With the `_redirect` file in `public`, this PR
Closes #68

**Comment by mrchrmn** [comment]
Meanwhile I got the table to show multiple translations and contexts.

**Pull request merged**
