### PR TITLE
How-to page added

### LINKED ISSUE #240: Sign in form should not reset after wrong email / password
I don't want to enter my email address again if I wasn't quick enough. Nor do I want to be interrupted as I correct my password.

Quick fix: set timeout to 60 seconds.

### PR DESCRIPTION
**Pull request by danachen**
## Description
- /how-to houses a number of gifs showing how the app works
- form for log-in does not reset immediately upon wrong username/password input

- closes #238 
- closes #240

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### CODE REVIEW

**Comment by mrchrmn** [comment]
It's great to have the gifs, but am not fond of the two column checker board layout with the large headings. I think I would prefer one column with full-width gifs, or at least always (smaller) caption left, gif right. 

And I would rather put theme toggling at the bottom. It is a nice feature, but the text handling is more important.

**Comment by danachen** [comment]
> It's great to have the gifs, but am not fond of the two column checker board layout with the large headings. I think I would prefer one column with full-width gifs, or at least always (smaller) caption left, gif right.
> 
> And I would rather put theme toggling at the bottom. It is a nice feature, but the text handling is more important.

Thanks for the feedback! Agree with the theme toggling. Will see what Eamon thinks about the layout.

**Comment by mrchrmn** [comment]
Oh, and also, the gifs are super fast over here. If I didn't know the app, I wouldn't be able to make out what's happening.

**Comment by danachen** [comment]
> Oh, and also, the gifs are super fast over here. If I didn't know the app, I wouldn't be able to make out what's happening.

👍 Good to know. I'll slow it down!

**Comment by mrchrmn** [comment]
Is it a global speed change or can you be more granular with whatever software you're using? I think whenever a new page loads, there should be a longer pause to get oriented.

**Comment by danachen** [comment]
> Is it a global speed change or can you be more granular with whatever software you're using? I think whenever a new page loads, there should be a longer pause to get oriented.

I can be particular with each recording.

**Comment by danachen** [comment]
- Updated with new gifs
- Updated footer hover colour for light theme
- Question: Footer /About only appears to logged in users. Should we make this available to all users regardless of logged in state?

**Comment by mrchrmn** [comment]
I think we only included About as a means to offer front page content to logged-in users. Having for anyone would duplicate content.

**Comment by mrchrmn** [comment]
Love the new gifs (on my phone, have to check PC tomorrow).

**Pull request merged**
