### PR TITLE
Settings page & copy for landing/about

### PR DESCRIPTION
**Pull request by danachen**
## Description

- Copy for landing/about page
- Setting page formatted, three sections work as separate forms for changes in user information
- Added back-end route/services, and a couple of front-end services

Still need to work on:
- Proper success/failure messages not showing yet (for now, test by making changes and checking database for updated values)
- Existing language settings not loading properly on first render yet
- Re-work error rendering

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| x  | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### CODE REVIEW

**Comment by mrchrmn** [comment]
Is this ready for testing and review? Then you can turn off the "draft" setting.

**Comment by eamon0989** [comment]
Changing the language in settings doesn't provide any confirmation as to whether it has worked or not. Also if the learn language is changed, it should also update in the navbar right? Otherwise if you prefer I can hide the langauge dropdown while in settings so as to avoid confusion.

**Comment by eamon0989** [comment]
Great job with the settings layout btw, I really like what you've done.

**Comment by danachen** [comment]
> 

I'm adding in error validation and success/failure messages today :grin:

**Comment by eamon0989** [comment]
Also changing the username doesn't indicate whether it was successful or not. If it is successful, the username displayed to in the left column should be updated :)

**Comment by eamon0989** [comment]
> > 
> 
> I'm adding in error validation and success/failure messages today 😁

Oh perfect 😁  I'll merge this then, great job 👏🏼

**Pull request merged**
